### ISSUE TITLE
Exception in thread "main" java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by JapuDCret** [thetric/ilias-downloader-cli#14]
after I selected I wanted to download all courses, the CLI crashed:
```
Exception in thread "main" java.lang.NoSuchMethodError: java.util.stream.Stream.iterate(Ljava/lang/Object;Ljava/util/function/Predicate;Ljava/util/function/UnaryOperator;)Ljava/util/stream/Stream;
        at com.github.thetric.iliasdownloader.cli.sync.ItemDownloadingItemVisitor.resolvePathOfParent(ItemDownloadingItemVisitor.kt:78)
        at com.github.thetric.iliasdownloader.cli.sync.ItemDownloadingItemVisitor.resolvePathAndCreateMissingDirs(ItemDownloadingItemVisitor.kt:71)
        at com.github.thetric.iliasdownloader.cli.sync.ItemDownloadingItemVisitor.handleFile(ItemDownloadingItemVisitor.kt:49)
        at com.github.thetric.iliasdownloader.service.webparser.impl.course.CourseSyncServiceImpl.walkIliasItemNode(CourseSyncServiceImpl.kt:134)
        at com.github.thetric.iliasdownloader.service.webparser.impl.course.CourseSyncServiceImpl.access$walkIliasItemNode(CourseSyncServiceImpl.kt:18)
        at com.github.thetric.iliasdownloader.service.webparser.impl.course.CourseSyncServiceImpl$visit$1.apply(CourseSyncServiceImpl.kt:56)
        at com.github.thetric.iliasdownloader.service.webparser.impl.course.CourseSyncServiceImpl$visit$1.apply(CourseSyncServiceImpl.kt:18)
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.util.ArrayList$ArrayListSpliterator.tryAdvance(Unknown Source)
        at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
        at com.github.thetric.iliasdownloader.service.webparser.impl.course.CourseSyncServiceImpl.visit(CourseSyncServiceImpl.kt:63)
        at com.github.thetric.iliasdownloader.service.webparser.impl.course.CourseSyncServiceImpl.walkIliasItemNode(CourseSyncServiceImpl.kt:130)
        at com.github.thetric.iliasdownloader.service.webparser.impl.course.CourseSyncServiceImpl.access$walkIliasItemNode(CourseSyncServiceImpl.kt:18)
        at com.github.thetric.iliasdownloader.service.webparser.impl.course.CourseSyncServiceImpl$visit$1.apply(CourseSyncServiceImpl.kt:56)
        at com.github.thetric.iliasdownloader.service.webparser.impl.course.CourseSyncServiceImpl$visit$1.apply(CourseSyncServiceImpl.kt:18)
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.util.ArrayList$ArrayListSpliterator.tryAdvance(Unknown Source)
        at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
        at com.github.thetric.iliasdownloader.service.webparser.impl.course.CourseSyncServiceImpl.visit(CourseSyncServiceImpl.kt:63)
        at com.github.thetric.iliasdownloader.service.webparser.impl.course.CourseSyncServiceImpl.walkIliasItemNode(CourseSyncServiceImpl.kt:130)
        at com.github.thetric.iliasdownloader.service.webparser.impl.course.CourseSyncServiceImpl.access$walkIliasItemNode(CourseSyncServiceImpl.kt:18)
        at com.github.thetric.iliasdownloader.service.webparser.impl.course.CourseSyncServiceImpl$visit$1.apply(CourseSyncServiceImpl.kt:56)
        at com.github.thetric.iliasdownloader.service.webparser.impl.course.CourseSyncServiceImpl$visit$1.apply(CourseSyncServiceImpl.kt:18)
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.util.ArrayList$ArrayListSpliterator.tryAdvance(Unknown Source)
        at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
        at com.github.thetric.iliasdownloader.service.webparser.impl.course.CourseSyncServiceImpl.visit(CourseSyncServiceImpl.kt:63)
        at com.github.thetric.iliasdownloader.service.webparser.impl.WebIliasService.visit(WebIliasService.kt:38)
        at com.github.thetric.iliasdownloader.cli.SyncController.executeSync(SyncController.kt:39)
        at com.github.thetric.iliasdownloader.cli.SyncController.startSync(SyncController.kt:28)
        at com.github.thetric.iliasdownloader.cli.CliController.startCliController(CliController.kt:41)
        at com.github.thetric.iliasdownloader.cli.CliKt.main(Cli.kt:30)
```

so I could login and even view all the subscribed courses.

my Java version:
```
java version "1.8.0_162"
Java(TM) SE Runtime Environment (build 1.8.0_162-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.162-b12, mixed mode)
```

I was running version 3.2.0 from the Github releases tab

**Comment by JapuDCret** [comment]
Thanks, works like a charm with Java 10
```
java version "10.0.1" 2018-04-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.1+10, mixed mode)
```

maybe change the Java Target Version in Gradle to Java 9, so the MANIFEST of the JAR file indicates with which Java version it is compatible

https://github.com/thetric/ilias-downloader-cli/blob/master/build.gradle#L27
