### ISSUE TITLE
ILIAS Login not working

### ISSUE THREAD

**Issue by tobire** [thetric/ilias-downloader-cli#17]
My ILIAS Login is not working eventhough the password is fine.

Log:

> Settings path: ./.ilias-downloader.json 
XXXXXXs password: 
Logging in at https://www.ilias.fh-dortmund.de/ilias/login.php 
[main] ERROR c.g.t.i.c.CliController - Login failed
com.github.thetric.iliasdownloader.service.exception.IliasAuthenticationException: Login at https://www.ilias.fh-dortmund.de/ilias/login.php failed. Invalid credentials
	at com.github.thetric.iliasdownloader.service.webparser.impl.webclient.OkHttpIliasWebClient.login(OkHttpIliasWebClient.kt:53) ~[ilias-downloader-cli-3.2.2.jar:na]
	at com.github.thetric.iliasdownloader.service.webparser.impl.WebIliasService.login(WebIliasService.kt:25) ~[ilias-downloader-cli-3.2.2.jar:na]
	at com.github.thetric.iliasdownloader.cli.LoginServiceImpl.createServiceFromConfig(LoginServiceImpl.kt:39) ~[ilias-downloader-cli-3.2.2.jar:na]
	at com.github.thetric.iliasdownloader.cli.LoginServiceImpl.connect(LoginServiceImpl.kt:27) ~[ilias-downloader-cli-3.2.2.jar:na]
	at com.github.thetric.iliasdownloader.cli.CliController.createIliasService(CliController.kt:67) ~[ilias-downloader-cli-3.2.2.jar:na]
	at com.github.thetric.iliasdownloader.cli.CliController.startCliController(CliController.kt:28) ~[ilias-downloader-cli-3.2.2.jar:na]
	at com.github.thetric.iliasdownloader.cli.CliKt.main(Cli.kt:36) ~[ilias-downloader-cli-3.2.2.jar:na]

The login at the given login URL with the same password works just fine.

**Comment by thetric** [comment]
Thanks for your bug report. I can reproduce this issue and will work on a solution

**Comment by thetric** [comment]
I've fixed the login, but the course sync is still failing
